### ISSUE TITLE
mujoco glfw does not work well under ubuntu env

### ISSUE THREAD

**Issue by syw-robotics** [tryingfly/nabo#1]
知乎而来，感谢作者开源，近日也在做双足的毕设项目，采用mujoco仿真（个人cpp水平有限，暂时使用mujoco python binding），暂无法解决此问题；

按照项目说明编译后，glfw无法正常显示，如图：
![image](https://github.com/tryingfly/nabo/assets/84261527/65f646b5-ecd1-45ec-be4e-828b45bf83ea)
![image](https://github.com/tryingfly/nabo/assets/84261527/f235a828-c37d-4889-8671-f7e3b455623a)

**Comment by syw-robotics** [comment]
已解决，直接cmake的时候报错，我复制替换了我本地用的3.1.2的mujoco的.so，重新下载了3.1.1的.so进行替换，编译运行成功

**Comment by tryingfly** [comment]
不太常看消息，不好意思！
很高兴您的问题已解决！



在 2024-03-02 20:19:29，"Siyuan Wang" ***@***.***> 写道：

已解决，直接cmake的时候报错，我复制替换了我本地用的3.1.2的mujoco的.so，重新下载了3.1.1的.so进行替换，编译运行成功
